### ISSUE TITLE
KeyError: 'packageUrl' error

### ISSUE THREAD

**Issue by ibapps39** [vvettoretti/pearson-downloader#1]
Hey:

Nice project here and I can get to the page where my books show, but after `Enter a filename for 'Digital Signal Processing: Principles, Algorithms and Applications, 5e.pdf' (leave empty to use default):` and hitting enter it crashes.

The errors I get are:
```
Traceback (most recent call last):
  File "pearson-downloader/main.py", line 39, in <module>
    pearson.download_book(book_id, filename,show_progress=True)
  File "pearson-downloader/PearsonLib.py", line 68, in download_book
    download = self.session.get(download_info["packageUrl"],
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'packageUrl'
```

edit: 09/08/2023 Busy with masters atm, but will check again this weekend!

**Comment by vvettoretti** [comment]
Hi there, could you kindly share the contents of the `download_info` variable?
You can add a print statement (`print(download_info)`) after **line 67** in `PearsonLib.py`, or use a debugger to see the code flow.

**Comment by monsterpac5** [comment]
Can concur, having same error on my end : KeyError: 'packageUrl'. Tryin to edit, just want to download my damn books lol

contents of variable : 
download = self.session.get(download_info["packageUrl"],
                                        headers={"etext-cdn-token": download_info["cdnToken"]},stream=True)

**Comment by vvettoretti** [comment]
You didn't include the contents of the **download_info** variable at runtime @monsterpac5.
My guess is that there are different types of books in the pearson app, which require different steps to download.
Unfortunately, since I don't have them in my account's library, I wasn't able to reverse engineer the download process for this certain types.
If you can share more context to the issue, I would be glad to help. You can also contact me on telegram.
If you already found a fix, you may make a pull request.

**Comment by ibapps39** [comment]
> Hi there, could you kindly share the contents of the `download_info` variable? You can add a print statement (`print(download_info)`) after **line 67** in `PearsonLib.py`, or use a debugger to see the code flow.

Will do, just busy with school atm.

**Comment by suDisdain** [comment]
I'm facing a similar issue. It's returning the following for download_info:
`{'message': 'InvalidEntitlement!!'}`

**Comment by jadc** [comment]
I added `print(download_info)`, and the output was `{'message': 'InvalidEntitlement!!'}`.

**Comment by vvettoretti** [comment]
Since I don't have enough information to fix the error, I am closing the issue. If somebody would be kind enough to share a pearson account which has this type of book, I could look into reverse engineering the download process.
